hw03
Morov78/rest-api-application pull request #2
Opened 2022-11-25 23:11 UTC by Morov78

2022-11-26 20:14 UTC, BohdanGres requested changes

2022-11-26 20:14 UTC, BohdanGres commented on controller/index.js
> +    if (errorsKeys.length === 1) {
я думаю що ось ці перевірки трохи зайві, без цього іфа кода буде менше а логіка збережеться та сама

2022-11-26 20:14 UTC, BohdanGres commented on server.js
> +require("dotenv").config();
гарна практика дадавати файл .env.example з переліком всіх змінних які треба для роботи
типу 
`
PORT=
DB_HOST=
`

2022-11-26 20:14 UTC, BohdanGres commented on server.js
> +mongoose
Краще конект до бд винеси в окремий файл
і його ліпше викликати до app.listen(3000, () => { 
 інакше в тебе виходить рейс кондішн
експресс в теорії може стартувати сервак дуже швидко а конект до бд відбуватиметься довше і перші запити всі зафейляться бо не достукаються в бд

2022-11-27 08:15 UTC, Morov78 commented on controller/index.js
> +    if (errorsKeys.length === 1) {
повидаляв перевірки

2022-11-27 08:16 UTC, Morov78 commented on server.js
> +require("dotenv").config();
добавив, мало інформації в інтернеті про цей допоміжний файл, надіюсь правильно описав

2022-11-27 08:17 UTC, Morov78 commented on server.js
> +mongoose
дякую, і справді база підключається набагато пізніше.

2022-11-27 19:05 UTC, BohdanGres commented on server.js
> +require("dotenv").config();
зазвичай сам файл .env лежить в гітігнорі але треба дати знати що в ньому має бути тому в рідмі описуючи степи один з них буде щось типу cp .env.example .env яка створи файл .env


сам файл має бути правильного фрмату 
типу так 
`
#port number for server
PORT=
#Add your connection string to MongoDB database
DB_HOST= 
`

2022-11-28 11:25 UTC, merged