control
Morov78/rest-api-application pull request #3
Opened 2022-12-08 21:43 UTC by Morov78

Привіт, перевірьте будь ласка :)

2022-12-09 12:52 UTC, BohdanGres requested changes
з валідацією все добре, більше питань до фільтрації, але загалом дуже хороша робота, трохи підтюнити дрібнички

2022-12-09 12:52 UTC, BohdanGres commented on api/index.js
> +
є така фішка, у великих проекта роути розибвають по файликам і ти потім підключаеш типу app.use('/user', userRouter); app.use('/contact', contactRouter); можеш спробувати зробиит якщо хочеш

2022-12-09 12:52 UTC, BohdanGres commented on service/contact.js
> +const listContacts = async (userId, favorite, page = 1, limit = 0) => {
а шо буде якщо не задані page  limit
ліпше дивись чи передали їх і тоді вже навішуй скіп і ліміт

2022-12-09 12:52 UTC, BohdanGres commented on service/token/createToken.js
> +require("dotenv").config();
оцю штуку достатньо викликати один раз в  головному індекс файлі

2022-12-09 12:52 UTC, BohdanGres commented on service/contact.js
> +const listContacts = async (userId, favorite, page = 1, limit = 0) => {
з овнером теж треба опційно зробити

2022-12-09 12:52 UTC, BohdanGres commented on controller/users/index.js
> +        .json({ message: "Subscription can be starter, pro or business" });
оцю штуку ліпше винести в мілдварку і ще до контроллера глянути що він в потрібних форматів, так ти не будеш зайвий раз чіпаи базу

2022-12-09 18:22 UTC, Morov78 commented on service/token/createToken.js
> +require("dotenv").config();
Прийняв, виправив

2022-12-09 19:27 UTC, Morov78 commented on api/index.js
> +
Про таке й думав, але не додумав... 
Розбив на окремі файли. Стало простіше для сприйняття. Дякую

2022-12-09 20:38 UTC, Morov78 commented on controller/users/index.js
> +        .json({ message: "Subscription can be starter, pro or business" });
виніс окремо перевірку

2022-12-09 22:15 UTC, Morov78 commented on service/contact.js
> +const listContacts = async (userId, favorite, page = 1, limit = 0) => {
переробив по підказці :)

2022-12-10 08:27 UTC, BohdanGres approved these changes

2022-12-10 09:03 UTC, merged