Hw 06
Morov78/rest-api-application pull request #5
Opened 2022-12-26 11:01 UTC by Morov78

2022-12-26 20:14 UTC, BohdanGres requested changes
так наче все окей, помучай докер ще

2022-12-26 20:14 UTC, BohdanGres commented on Dockerfile
> +FROM node
треба вказувати конкретну версію ноди

2022-12-26 20:14 UTC, BohdanGres commented on Dockerfile
> +FROM node
+ скоріш за все не буде працювати чрез докер і дев режим як варіант додай в пекедж джейсон команду якм всі маунти робить що б зміни в контейнері і локально сінкались

2023-01-04 08:51 UTC, Morov78 commented on Dockerfile
> +FROM node
запуск app в докері через команду:
docker-compose up -d.
база знаходиться в докер контейнері, прив"язана до app

2023-01-04 19:31 UTC, BohdanGres approved these changes
все супер, серйозний проєкт вже)

2023-01-04 19:34 UTC, merged